### ISSUE TITLE
[Help] Action generated by UI not working

### ISSUE THREAD

**Issue by nicknol** [Sian-Lee-SA/Home-Assistant-Switch-Manager#281] opened 2024-11-10 11:32 UTC
I am trying the most simple action for the single press and I get an error in the developer console.

```
- action: switch.toggle
  metadata: {}
  data: {}
  target:
    entity_id: switch.switch_3lt_socket
```
The code snippet was created by the UI, no manual intervention.
![grafik](https://github.com/user-attachments/assets/d9993503-abce-4457-95b9-d7ca75e5e474)

and I get in Developer Console:

`Object { code: "invalid_format", message: "extra keys not allowed @ data['action']. Got {'action': 'switch.toggle', 'metadata': {}, 'data': {}, 'target': {'entity_id': 'switch.switch_3lt_socket'}}" }`

**Comment by Sian-Lee-SA** [comment] 2024-11-11 00:12
You are literally the only person I have seen with this issue, there must be something you have done strange... What version of Home Assistant are you running?

Just tested the same code with an entity on my system and works fine. Can't reporduce!

**Comment by nicknol** [comment] 2024-11-11 06:09
Yes, I am surprised as well. the simple action code runs in developer tools, of course.
The issue is (for me) reproducable, I added one more switch: same code for the action, same error message.

I am running HA 2024.11.01

**Comment by Sian-Lee-SA** [comment] 2024-11-11 06:17
"The issue is (for me) reproducable" is not disputed but is not helpful if it can't be reporduced anywhere else on anyone elses systems as it shows no pattern or underlying issue, I would assume whatever is going on has something to do with how you've set things up or a recent HA update change which I also doubt as I'm sure more outcries wouldve been heard by now with the same issue.

Until there is a pattern or you find something damning then this will stay in limbo as like I said, it is not reproducable nor raised before.

**Comment by Sian-Lee-SA** [comment] 2024-11-11 06:32
Also when you uninstall, ensure config/.storage/switch_managfer is also removed

**Comment by nicknol** [comment] 2024-11-11 06:46
Thanks for the hint. 
 config/.storage/switch_manager was not removed during uninstallation.
 I uninstalled again, removed  config/.storage/switch_manager manually and installed again.
```

config/.storage/switch_manager looks empty and ok
{
  "version": 1,
  "minor_version": 1,
  "key": "switch_manager",
  "data": {
    "version": "2.0.3",
    "managed_switches": {}
  }
}
```

But the issue persists, any simple action gives the mentioned error message.

Will try to find anomalies ...

**Comment by Sian-Lee-SA** [comment] 2024-11-13 09:41
I going to go on s limb here, I take it the switch works fine but running from the UI doesn't. I just did a test on the latest version and found the error ONLY when using run from the UI but the switch operated normally.

**Comment by thewan056** [comment] 2024-11-13 12:25
If you meant that the switch did not work while using the "run" option from the 3 dot menu in switch manager but runs fine when you actually press the physical button, it did not.

When I meant that it didn't work, the action did not work at all regardless if i press the physical button or at using the "run" option.

**Comment by Sian-Lee-SA** [comment] 2024-11-13 12:37
Ok, well i got the same error but ran fine when saved and using the switch normally, so still can't reproduce this... And yes, "run" is tied to the UI and not a switch function or associated with how switch manager handles actions and their serquence in the background. I just don't want the 'run' function of the UI to convolute the issue in general and needs to be defined more apparently as again"run" is not a part of switch manager's running loop.

**Comment by Sian-Lee-SA** [comment] 2024-11-13 12:43
The error makes even more sense to be a UI issue from a recent update as the UI is a few updates behind which could have endpoints changed from what the UI was originally designed for. But makes less sense if the sequences etc aren't working if the switch and buttons are pressed naturally, so you saying it doesn't work in the background has me stumped

**Comment by nicknol** [comment] 2024-11-13 12:56
For me, the issue is _only_ related to the UI when trying to run the created action.
The action executed correctly after _saving_ it and then pressing the related button on the real switch.

Thanks a lot for immediately taking care.

**Comment by Sian-Lee-SA** [comment] 2024-11-13 13:12
Thanks for the clarification @nicknol which lines more towards my theory. Hopefully a near future UI update will remedy this but atleast the switches still works normally. Unfortunately @thewan056 I have no idea with your issue and can't really nail down what it is.

**Comment by cameronkelley** [comment] 2024-12-06 00:26
Just wanted to chime in that I have the same issue and after saving and testing it at the physical switch it does work properly same as @nicknol so it's definitely just a UI issue.
Thanks for that info, easy to bang your head against the wall with more complex troubleshooting and not try the simple steps.

@Sian-Lee-SA - Might be worth adding a note in the documentation about this and point to this issue to keep the clutter down. I can try and submit a PR soon with a basic note about it in the readme if you think it would be useful.

**Comment by Sian-Lee-SA** [comment] 2024-12-06 02:54
@cameronkelley Probably worth noting that the UI can expect some quirks as the sequence interface is directly used from HA core and editing the source is very limited. All functions and switch buttons should still execute normally even if the UI doesn't behave as intended.

Whether this should be noted up top or down FAQ I'm not sure yet. As there are other unexpected UI behaviours and issues that arent forseeable, it's best to generalise and warn that the UI doesn't always play nicely.

Will close this now though because "fixing" it isn't exactly planned and the core functionality still works. But again, it mostly boils down to the source of HA and how it's tailored towards their overall system. It will just be matter of seeing if future UI update might just happen to mysteriously work again(?) (honestly, never used the feature to know).

**Closed by Sian-Lee-SA** 2024-12-06 02:54 UTC

**Comment by cameronkelley** [comment] 2024-12-06 08:49
Sounds good. Seems like it could be a pretty simple message about the fact that HA's UI is always changing and to test if the physical switch works as expected before reporting an issue.

After looking at the readme, I'm not seeing an FAQ, but there is the troubleshooting section at the end. If I have time tomorrow, I'll do something quick to add it there for now and possibly structure it a bit more in the future. Ideally multiple people could eventually contribute to building a basic wiki, but that's not pressing and better for you to spend the time you have on the integration than dealing with docs. Thanks @Sian-Lee-SA

**Comment by RezzZ** [comment] 2025-06-11 10:22
I understand HA sometimes changes behaviour but shouldn't the option to actually test an action when setting it up in Switch Manager be one of the core functionalities of Switch Manager?
I really love Switch Manager.
The UI for Switch Manager seems the same as that from an automation, aren't they "hooking into the same piece of code" in HA for setting it up?
