### ISSUE TITLE
Broken on HA2024.8

### ISSUE THREAD

**Issue by adidoes** [Sian-Lee-SA/Home-Assistant-Switch-Manager#249] opened 2024-08-22 11:59 UTC
I'm trying this addon for the first time, I'm on HA 2024.8 and saving in the switch editor seems to alter the yaml in a way that breaks it (see screenshots below).

I suspect this is because HA changed the "service" keyword to "action" and maybe they're doing that automatically for the switch editor form too.

**Before save:**
<img width="366" alt="image" src="https://github.com/user-attachments/assets/5ee44ec5-3844-4d7c-a700-1e190dea422a">

YAML:

```yaml
- service: light.toggle
  data: {}
  target:
    entity_id: light.living_room_light
```

**After save:**
<img width="399" alt="image" src="https://github.com/user-attachments/assets/12d76b12-f036-4a14-8a63-56bf11bbbb57">

YAML:

```yaml
- data: {}
  target:
    entity_id: light.living_room_light
  action: light.toggle
```

I tried clearing cache/different browsers and even the mobile app so it doesn't seem to be a cache issue.

**Comment by rubin110** [comment] 2024-08-22 18:16
I'm hitting this issue too. It seems like whatever is validating if this is a UI editable line is searching for `service:` and not `action:`. Changing it to a `service:` brings the UI option back.

**Comment by rubin110** [comment] 2024-08-22 18:19
This is a dupe of #244. I recommend the maintainer keep the original bug open so that more duplicates don't show up (yes people should search, no they never will).

**Comment by Sian-Lee-SA** [comment] 2024-08-23 07:03
I will close this but reopen the other as initially I thought the user was manually adding action to their yaml code but turns out HA is doing it in the background. Sorry, just forgot to reopen...

**Closed by Sian-Lee-SA** 2024-08-23 07:03 UTC
