### ISSUE TITLE
Any way to reduce number of new releases?

### ISSUE THREAD

**Issue by jhhbe** [Sian-Lee-SA/Home-Assistant-Switch-Manager#59] opened 2023-01-05 18:55 UTC
Not surprised people are interested in this and that new switches are added regularly. Would be great if new switches could be added without a new release and that new releases are reserved for additional functionality (not that I'm missing anything). Would be cool to split functionality versus content, though I understand it may sound like an unreasonable ask.

Very happy with the clean up in my automations as a result of installing this one!

**Comment by Sian-Lee-SA** [comment] 2023-01-05 19:57
New releases also comes with bug fixes or optimisation and is still currently beta. I also needed to test the release it helper as to ensure version bump and other things were correctly committed prior.. Just out of curiosity, is there some sort of inconvenience caused by new release? If so could you explain the inconvenience?

**Comment by jhhbe** [comment] 2023-01-05 20:20
Inconvenience is not related to Switch Manager, it behaves very well. An update through HACS requires a restart and I have some sensors that don't behave well. I should consider using retain flag in MQTT autodiscovery for those.
I understand it's early days for this one, though it already does all I could hope for - templates in actions were working the day I first saw it. But if you look at the number of devices supported in zigbee2mqtt then that potentially could be a lot of releases.

**Comment by Sian-Lee-SA** [comment] 2023-01-05 20:24
Oh OK, I don't use HACS so I don't know what happens there with new releases, if you have everything working correctly, then there's no need to update? This is generally how developing works. deCONZ and others that I know of makes a new release for new devices. There's just going to be more releases at the beginning as the devices start streaming in then slows down once most are covered

**Closed by Sian-Lee-SA** 2023-01-05 20:24 UTC

**Comment by Sian-Lee-SA** [comment] 2023-01-05 20:26
But the releases as of late with blueprints has also included code or fixes from other blueprints that needed to be addressed right away to avoid invalid configs

**Comment by jhhbe** [comment] 2023-01-06 07:31
Thanks for spending the time to explain! HACS is a repository for community integrations and I think it will make it easier for people to use/discover this. So even if you don't use it, thanks for including it as it is very convenient.
At some point it might be worth to look at zigbee2mqtt for inspiration, they deliver a large number of items and have their config file in one file rather than individual files (which at this stage  most likely is the safest way for now to deliver).

**Comment by Sian-Lee-SA** [comment] 2023-01-06 07:37
I've been using Zigbee2MQTT for over 2 years or so ;) and I understand they do it that way and have a seperate repo for it but even when a new device gets updated, it still needs to be realeased with that updated added devices. Many developers handle this differently qand I feel it's more convenient and accessable for end users to quickly copy and edit a blueprint but I understand and respect your insight.

**Comment by noxhirsch** [comment] 2023-01-06 10:17
@jhhbe A while ago I have created an auto-skip automation for another integration I don't want to update often. To update the integration you have to go to the skipped updates in Home Assistant or update in HACS.

```
alias: Auto-Skip Updates
description: ""
trigger:
  - platform: state
    entity_id:
      - update.smartthinq_lge_sensors_update
    to: "on"
action:
  - service: update.skip
    data: {}
    target:
      entity_id: "{{ trigger.entity_id }}"
mode: single
```
