### ISSUE TITLE
Please add Paulmann 4 Tab Switch (Zigbee2mqtt)

### ISSUE THREAD

**Issue by echicor** [Sian-Lee-SA/Home-Assistant-Switch-Manager#181] opened 2023-11-08 14:25 UTC
Hi,
can you please add the "Paulmann 4 Button Switch" in your next release ? I'v written the yaml-file and also add a png-file to this Issue. So everybody can use it with the next release ;-)

> name: Paulmann 4 Button Switch
> service: Zigbee2MQTT
> event_type: mqtt
> mqtt_topic_format: zigbee2mqtt/+/action
> buttons:
> # top left ( I )
>   - x: 40
>     y: 40
>     width: 50
>     height: 80
>     actions:
>       - title: press
>         conditions:
>           - key: payload
>             value: 'on_1'
>       - title: hold
>         conditions:
>           - key: payload
>             value: brightness_move_up_1
>       - title: hold (released)
>         conditions:
>           - key: payload
>             value: brightness_stop_1 
> # top right ( O )
>   - x: 158
>     y: 40
>     width: 50
>     height: 80
>     actions:
>       - title: press
>         conditions:
>           - key: payload
>             value: 'on_2'
>       - title: hold
>         conditions:
>           - key: payload
>             value: brightness_move_up_2
>       - title: hold (released)
>         conditions:
>           - key: payload
>             value: brightness_stop_2    
>             
>             
> # bottom left ( I )
>   - x: 40
>     y: 125
>     width: 50
>     height: 80
>     actions:
>       - title: press
>         conditions:
>           - key: payload
>             value: 'off_1'
>       - title: hold
>         conditions:
>           - key: payload
>             value: brightness_move_down_1
>       - title: hold (released)
>         conditions:
>           - key: payload
>             value: brightness_stop_1       
>             
>             
> # bottom right ( O )
>   - x: 158
>     y: 125
>     width: 50
>     height: 80
>     actions:
>       - title: press
>         conditions:
>           - key: payload
>            value: 'off_2'
>       - title: hold
>         conditions:
>           - key: payload
>             value: brightness_move_down_2
>       - title: hold (released)
>         conditions:
>           - key: payload
>             value: brightness_stop_2

![zigbee2mqtt-paulmann-4-button-switch](https://github.com/Sian-Lee-SA/Home-Assistant-Switch-Manager/assets/80566077/112556a9-4ff8-460b-ad28-72cabd2677de)

**Comment by Sian-Lee-SA** [comment] 2023-11-09 08:47
You will need to create a PR (duplicate of https://github.com/Sian-Lee-SA/Home-Assistant-Switch-Manager/issues/168)

**Closed by Sian-Lee-SA** 2023-11-09 08:47 UTC

**Comment by ceear** [comment] 2024-12-26 20:57
https://github.com/Sian-Lee-SA/Home-Assistant-Switch-Manager/pull/307
