### ISSUE TITLE
Does not work with HA 2023.12.0

### ISSUE THREAD

**Issue by GB-1972** [Sian-Lee-SA/Home-Assistant-Switch-Manager#197] opened 2023-12-08 08:03 UTC
This great tool has stopped working since version 2023.12.0. 
Error loading the integration.

**Comment by Sian-Lee-SA** [comment] 2023-12-08 08:09
This has been addressed numerous times
Closing as duplicate https://github.com/Sian-Lee-SA/Home-Assistant-Switch-Manager/issues/185

**Closed by Sian-Lee-SA** 2023-12-08 08:09 UTC

**Comment by D3SL** [comment] 2023-12-09 02:30
@GB-1972 I think the issue is with HACS, I didn't get notified by HACS that there was an update for Switch Manager until after I'd already tried rebooting HA a few times and posted here.

**Comment by Sian-Lee-SA** [comment] 2023-12-09 09:44
I don't use HACS (only added my repo to their list) so I can't comment on how or what is going on with HACS but I know this issue has been fixed which was released before 2023.12 even came out. I would assume some people might figure out there is an issue with HACS if that's their method of installing once they see the release on this repo and compare to the version on HACS.

**Comment by GB-1972** [comment] 2023-12-09 11:41
Thank you. After updating the Integration manually, it works Fine.
